tam:
#     0        1        2        3        4        5        6        7
- [ 0.25  ,  0.0   ,  0.0   , -0.25  ,  0.25  ,  0.0   ,  0.0   , -0.25  ]  # X
- [-0.25  ,  0.0   ,  0.0   , -0.25  ,  0.25  ,  0.0   ,  0.0   ,  0.25  ]  # Y
- [ 0.0   , -0.25  , -0.25  ,  0.0   ,  0.0   , -0.25  , -0.25  ,  0.0   ]  # Z
- [ 0.0   , -0.25  , -0.25  ,  0.0   ,  0.0   ,  0.25  ,  0.25  ,  0.0   ]  # ROLL
- [ 0.0   ,  0.25  , -0.25  ,  0.0   ,  0.0   ,  0.25  , -0.25  ,  0.0   ]  # PITCH
- [-0.25  ,  0.0   ,  0.0   ,  0.25  ,  0.25  ,  0.0   ,  0.0   , -0.25  ]  # YAW
